-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "lastScanned" TIMESTAMP(3),
ADD COLUMN     "qrGenerated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "scanCount" INTEGER NOT NULL DEFAULT 0;
